import sys
from PIL import Image, ImageDraw

def process(input_path, output_path):
    img = Image.open(input_path).convert("RGBA")
    w, h = img.size
    
    # Create a mask
    mask = Image.new('L', (w, h), 0)
    draw = ImageDraw.Draw(mask)
    
    # We need to find the bounds of the circle.
    # We can scan from the outside to find the first non-white pixel.
    # But usually the logo generated by DALL-E has a little margin.
    # Let's find the first non-white pixel from the left, right, top, bottom.
    left, right, top, bottom = w, 0, h, 0
    pixels = img.load()
    
    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y]
            if not (r > 240 and g > 240 and b > 240):
                if x < left: left = x
                if x > right: right = x
                if y < top: top = y
                if y > bottom: bottom = y
                
    # Now we have the bounding box. The circle is inside it.
    # Add a small padding if necessary, but usually the bounding box IS the circle.
    bbox = [left, top, right, bottom]
    
    # Draw a smooth circle in the mask
    draw.ellipse(bbox, fill=255)
    
    # Apply the mask to a new image
    out = Image.new("RGBA", (w, h))
    out.paste(img, (0, 0), mask=mask)
    
    # Crop to bounding box
    out = out.crop(bbox)
    
    out.save(output_path)
    print(f"Saved transparent logo to {output_path}")

if __name__ == '__main__':
    process(sys.argv[1], sys.argv[2])
